### ISSUE TITLE
My development is on the win10, can I not use the ROS system and transplant to Win10, visualization with open3d or any other solution instead?

### ISSUE THREAD

**Issue by WestbrookZero** [felixchenfy/ros_openpose_rgbd#2]

**Comment by felixchenfy** [comment]
Hi, I'm not familar with setting up ROS win10. sorry about that

**Comment by WestbrookZero** [comment]
What I mean is that i don't use ros on windows，is it feasible to use open3d instead of ros visualization on the windows?

**Comment by felixchenfy** [comment]
yes it's feasible.
Need to replace the input/output source --- the main program reads images
from a ros topic and publishes the result to other ros topics for display.
You will need to replace those ros topic with what you want

**Comment by WestbrookZero** [comment]
Thanks for your answer ! i will try if open3d can replace ros rviz to display!

**Comment by WestbrookZero** [comment]
Traceback (most recent call last):
  File "D:/Projects/Python/AzureKinectDetect/1/detect01.py", line 167, in <module>
    rgbd.color_image(), is_return_joints=True)
  File "D:\Projects\Python\AzureKinectDetect\1\lib_openpose_detector.py", line 85, in detect
    self._opWrapper.emplaceAndPop([datum])
TypeError: emplaceAndPop(): incompatible function arguments. The following argument types are supported:
    1. (self: pyopenpose.WrapperPython, arg0: std::vector<std::shared_ptr<op::Datum>,std::allocator<std::shared_ptr<op::Datum> > >) -> bool

Invoked with: <pyopenpose.WrapperPython object at 0x0000024539BA0880>, [<pyopenpose.Datum object at 0x0000024539BA0A40>]

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
Process finished with exit code 1

when i run .py reported the error , Is it related to the openpose version? what is the openpose version version you use? i am using openpose1.7?
