### ISSUE TITLE
AttributeError: 'RgbdImage' object has no attribute '_camera_pose'

### ISSUE THREAD

**Issue by yani-rl-ai** [felixchenfy/ros_openpose_rgbd#5]
Hi @felixchenfy  
when i tried this command : 

**3.1.2. lib_draw_3d_joints.py**
python lib_draw_3d_joints.py
roslaunch ros_openpose_rgbd run_rviz.launch

i got this following error : 
python lib_draw_3d_joints.py
Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
[INFO] [1610807311.947765]: RvizMarker.init(): frame_id=base, topic_name=visualization_marker
Traceback (most recent call last):
  File "lib_draw_3d_joints.py", line 425, in <module>
    test_visualize_3d_joints()
  File "lib_draw_3d_joints.py", line 403, in test_visualize_3d_joints
    hand_joints[:, i, :, :])
  File "lib_draw_3d_joints.py", line 239, in __init__
    self.set_joints(rgbd, body_joints, hand_joints)
  File "lib_draw_3d_joints.py", line 248, in set_joints
    self._body = Body(id_body, rgbd, body_joints)
  File "lib_draw_3d_joints.py", line 181, in __init__
    super(Body, self).__init__(*args)
  File "lib_draw_3d_joints.py", line 61, in __init__
    self._create_3d_joints(joints)
  File "lib_draw_3d_joints.py", line 132, in _create_3d_joints
    joints_xyz_in_world = change_joints_coordinate_to_world()
  File "lib_draw_3d_joints.py", line 127, in change_joints_coordinate_to_world
    T_camera = self._rgbd.camera_pose()  # 4x4
  File "/home/kubotalab/open3dtest_ws/src/ros_openpose_rgbd/utils/lib_rgbd.py", line 62, in camera_pose
    return self._camera_pose
AttributeError: 'RgbdImage' object has no attribute '_camera_pose'

can you help me?

**Comment by felixchenfy** [comment]
Hey, it looks like some ROS problem
```
Unable to register with master node [http://localhost:11311]: master may not be running yet.
```
Did you run `roscore`?
